services:
  - type: web
    name: restaurant-backend
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DEBUG
        value: 'False'

databases:
  - name: restaurant-db
    plan: free
